name: Check PR
on: 
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Linting and Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node JS LTS
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install npm dependencies
      run: npm install

    - name: Run build steps
      run: npm run build

    - name: Run default tests
      run: npm test
